apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploydaemon
  name: deploydaemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploydaemon
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploydaemon
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
