# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../../base
nameSuffix: -dev
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: my-app:latest
    newTag: dev-123