# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -dev
resources:
  - deployment.yaml
  - namespace.yaml
images:
  - name: my-app:latest
    newTag: dev-123