apiVersion: v1
kind: Pod
metadata:
  name: my-pod-cka
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: my-pvc-cka
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: task-pv-storage

