apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role-cka
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - list
  - get
