apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
  generation: 1
  name: cache-daemonset
  namespace: default
  resourceVersion: "5779"
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cache
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: Always
        name: cache-container
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
