apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: myapp
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: myapp-map
    literals:
      - KEY=value