# overlays/prod/deployment.yaml
---
apiVersion: apps/v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    env: prod
spec:
  replicas: 2