# overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -prod
namespace: prod
resources:
  - deployment.yaml
  - namespace.yaml
images:
  - name: my-app:latest
    newTag: prod-456