apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab4-volume
  labels:
    type: local
spec:
  storageClassName: lab4
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage"
