apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  #This part will run only during container initialization
  initContainers:
  - name: install
    image: busybox
    command: ["sleep", "30"]