# A common, base deployment manifest.
# Note that this doesn't specify a namespace. Kustomize will add one later.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-busybox-app
  labels:
    app: busybox
spec:
  replicas: 1 # This will be overridden by the overlays.
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox-container
          image: busybox
          command: ["sh", "-c", "echo 'Hello from Kustomize!' && sleep 3600"]