apiVersion: v1
kind: Pod
metadata:
  name: gray-pod-deploy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: color
            operator: In
            values:
            - gray
  containers:
  - name: gray-pod-deploy
    image: nginx