apiVersion: v1
kind: Pod
metadata:
  name: red-pod-deploy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: color
            operator: In
            values:
            - red
  containers:
  - name: red-pod-deploy
    image: nginx