apiVersion: v1
kind: Pod
metadata:
  name: green-pod-deploy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: color
            operator: In
            values:
            - green
  containers:
  - name: green-pod-deploy
    image: nginx