apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "taint-b"
        operator: "Equal"
        value: "example"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx:latest
